### ISSUE TITLE
installer check sentora installation and version

### ISSUE THREAD

**Issue by andykimpe** [auxio/Zentora#4]
recommend add code on your installer

<code>if [ -d "/etc/sentora/panel" ]; then

VERSION_SENTORA=$(setso --show dbversion)

echo "Install for Sentora version $VERSION_SENTORA"

sleep 10

else

echo "Sory Sentora not intalled on your server"

echo "please install sentora http://docs.sentora.org/?node=7"

exit

fi</code>

**Comment by Ron-e** [comment]
It has taken a while but i added it.. 26ace95
